language: python
python:
  - "3.7"

services:
  - docker

jobs:
  include:
     - 
        stage: "Install requirements and lint"
        script:
           - pip install -r mysql_cluster_manager/requirements.txt
           - cd mysql_cluster_manager && pylint src
           - mysql_cluster_manager/src/mysql_cluster_manager.py
     - 
        stage: "Build docker"
        script: docker build -t jnidzwetzki/mysql-ha-cloud:latest -f Dockerfile-mysql .
     - 
        stage: "Deploy docker"
        script: 
               - docker build -t jnidzwetzki/mysql-ha-cloud:latest -f Dockerfile-mysql .
               - echo "$DOCKER_PASSWORD" | docker login -u jnidzwetzki --password-stdin
               - docker push jnidzwetzki/mysql-ha-cloud:latest
        if: branch = main
