language: python
python:
  - "3.7"

services:
  - docker

install:
  - pip install -r cluster_manager/requirements.txt
  - docker build -t jnidzwetzki/mysql-ha-cloud:debian10 -f Dockerfile-mysql .

script: true
