language: python
python:
  - "3.7"

services:
  - docker

jobs:
  include:
     - 
        script: pip install -r mysql_cluster_manager/requirements.txt
     - 
        script: cd mysql_cluster_manager && pylint src
     - 
        stage: "Build docker"
        script: build -t jnidzwetzki/mysql-ha-cloud:debian10 -f Dockerfile-mysql .
     - 
        stage: "Deploy docker"
        on: 
	   branch: main
	script: echo Deploy to Docker

