version: "3.8"

networks:
  backend:

services:
  consul:
    image: consul:1.8
    networks:
       backend:
          aliases:
             - consul_cluster
    environment:
      - CONSUL_BIND_INTERFACE=eth0
    command: agent -ui -data-dir /consul/data -server -client 0.0.0.0 -retry-join consul_cluster -bootstrap-expect=3 
    deploy:
      replicas: 3
      endpoint_mode: dnsrr
      placement:
        max_replicas_per_node: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure

  mysql:
    image: jnidzwetzki/mysql-ha-cloud:latest
    networks:
       backend:
    environment:
      - CONSUL_BIND_INTERFACE=eth0
      - CONSUL_BOOTSTRAP_SERVER=consul_cluster
      - MINIO_ACCESS_KEY=minio
      - MINIO_SECRET_KEY=minio123
      - MINIO_URL=http://minio:9000
      - MYSQL_ROOT_PASSWORD=verysecret123
      - MYSQL_BACKUP_USER="backup_user"
      - MYSQL_BACKUP_PASSWORD="backup_secret"

    deploy:
      replicas: 3
      placement:
        max_replicas_per_node: 1
      update_config:
        parallelism: 1
        delay: 60s
      restart_policy:
        condition: on-failure

  minio:
    image: minio/minio:RELEASE.2020-10-18T21-54-12Z
    networks:
       backend:
          aliases:
             - minio_endpoint
    ports:
       - 9000:9000
    environment:
       - MINIO_ACCESS_KEY=minio
       - MINIO_SECRET_KEY=minio123
    command: server /data

 
