name: Build project
 
on: [push, pull_request]

jobs:
  compile:
    runs-on: ubuntu-22.04
    
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v2
      - name: Setup python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
           python -m pip install -r mysql_cluster_manager/requirements.txt
           cd mysql_cluster_manager
           pylint src
           src/mysql_cluster_manager.py --help
           
      - name: Build docker image
        run: docker build -t jnidzwetzki/mysql-ha-cloud:latest -f Dockerfile-mysql .

      - name: Login at docker hub
        run: | 
           docker login -u ${{secrets.DOCKER_USER}} -p ${{secrets.DOCKER_PASSWORD}} 

      - name: Push image
        if: github.ref == 'refs/heads/main'
        run: |
           docker push jnidzwetzki/mysql-ha-cloud:latest
